# Copy this file to cinchbot.yml and make the appropriate modifications.
directories:
  main: ~/cinchbot
  plugins:
    core:  plugins/core
    extra: plugins/enabled
networks:
  dalnet:
    server: irc.dal.net
    realname: King Conch
    user: cinchbot
    nicks: 
      - CinchBot
      - KingConch
    channels:
      - '#cinchbot'
    sasl:
      username: username
      password: password
  freenode:
    server: irc.freenode.net
    realname: King Conch
    user: conchbot
    nick: conchbot
    channels:
      - '#cinch-bots'
    sasl:
      username: username
      password: password
