# Copy this file to cinchbot.yml and make the appropriate modifications.

# Our main bot run dir, directories listed below will be relative to this
# unless a full path is given.
dir_main: ~/cinchbot
log_file: cinchbot.log

# Plugin directories
plugins:
  core:  plugins/core
  extra: plugins/enabled

# The networks we'll connect to
networks:

  # Default entries, may be overwritten per server
  defaults:
    realname: CinchBot
    user: cinchbot
    nicks: 
      - CinchBot

  dalnet:
    server: irc.dal.net
    channels:
      - '#cinchbot'
    sasl:
      username: username
      password: password
  freenode:
    server: irc.freenode.net
    nick: conchbot
    channels:
      - '#cinch-bots'
    sasl:
      username: username
      password: password
